#!/bin/bash

# Define variables
job_name="job1"
date="2024-04-23"  # Specify the date in yyyy-mm-dd format
status_to_update="3"

# Find the maximum ID and maximum Sub ID for the given job name and date
max_id_subid=$(awk -F"|" -v job_name="$job_name" -v date="$date" '$1 == job_name && $4 == date && ($2 > max_id || max_id == "") { max_id = $2; max_subid = $3 } END { print max_id, max_subid }' data.csv)

# Update the CSV file
awk -F"|" -v job_name="$job_name" -v date="$date" -v status="$status_to_update" -v max_id_subid="$max_id_subid" 'BEGIN { OFS=FS } NR == 1 || ($1 == job_name && $2 == (split(max_id_subid, id_subid, " ")[1]) && $3 == (split(max_id_subid, id_subid, " ")[2])) { if (NR > 1) { $5 = status; $6 = strftime("%Y-%m-%d %H:%M:%S") } print } NR > 1 && $1 != job_name && ($2 != (split(max_id_subid, id_subid, " ")[1]) || $3 != (split(max_id_subid, id_subid, " ")[2])) { print }' data.csv > temp.csv && mv temp.csv data.csv



awk -F"|" -v job_name="job1" -v date="2024-04-23" -v status="3" 'BEGIN { OFS=FS } NR == 1 || ($1 == job_name && $4 == date) { if (NR > 1 && $2 > max_id) { max_id = $2; max_subid = $3; } if (NR > 1 && $2 == max_id && $3 > max_subid) { max_subid = $3; } if (NR > 1 && $1 == job_name && $2 == max_id && $3 == max_subid) { $5 = status; $6 = strftime("%Y-%m-%d %H:%M:%S"); } print }' data.csv > temp.csv && mv temp.csv data.csv


awk -F"|" -v jn="$job_name" -v id_subid="$max_id_subid" 'BEGIN { OFS=FS } NR == 1 || ($1 == jn && $2 == (split(id_subid, id_subid_array, " ")[1]) && $3 == (split(id_subid, id_subid_array, " ")[2])) { if (NR > 1) { $5 = "3"; $6 = strftime("%Y-%m-%d %H:%M:%S") } print }' "$data_file" > temp.csv && mv temp.csv "$data_file"


awk -F"|" -v job_name="$job_name" -v status="$status" -v max_id="$max_id" -v max_subid="$max_subid" 'BEGIN { OFS=FS } NR > 1 && $1 == job_name && $2 == max_id && $3 == max_subid { $5 = status; print } NR > 1 && !($1 == job_name && $2 == max_id && $3 == max_subid) { print }' data.csv




id_subid=$(awk -F"," -v jn="$job_name" '
    NR > 1 && $1 == jn {
        if ($2 > max_id || max_id == "") {
            max_id = $2;
            max_subid = $3
        } else if ($2 == max_id && $3 > max_subid) {
            max_subid = $3
        }
    }
    END {
        print max_id, max_subid
    }
' "$data_file")



max_id_subid=$(awk -F"," -v jn="$job_name" 'NR > 1 && $1 == jn && ($2 > max_id || max_id == "") { max_id = $2; max_subid = $3 } END { print max_id, max_subid }' "$data_file")








awk -F"," -v jn="job1" 'NR > 1 && $1 == jn { if ($2 > max_id || max_id == "") { max_id = $2; max_subid = $3 } else if ($2 == max_id && $3 > max_subid) { max_subid = $3 } } END { print max_id, max_subid }' "data.csv"
